---
- name: Configure network devices
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Configure interface FastEthernet6/0
      ios_command:
        commands:
          - conf t
          - interface FastEthernet6/0
          - ip address 192.168.4.5 255.255.255.0
      register: result_interface_config
    - name: Configure SSH and username
      ios_config:
        lines:
          - conf t
          - username ahmed12 secret ahmed12
          - crypto key generate rsa encryption modulus 1024
          - line vty 0 4
          - transport input ssh
          - login local
      register: result_SSH

    - name: Configure OSPF
      ios_config:
        lines:
          - router ospf 2
          - network 0.0.0.0 255.255.255.255 area 2
      register: result_ospf

    # Add more tasks as needed

    - name: Print task results
      debug:
        var: item
      with_items:
        - result_interface_config
        - result_SSH
        - result_ospf
