---
- name: Fetch running configuration from routers
  hosts: r1
  gather_facts: false
  connection: local

  tasks:
    - name: Fetch running configuration
      ios_command:
        commands:
          - show run
      register: config_output
