---
- name: Fetch running configuration from Cisco routers
  hosts: router
  gather_facts: no
  tasks:
    - name: Fetch running configuration
      ios_command:
        commands:
          - show running-config
      register: config_output
