---
- name: Initial Playbook
  hosts: all
  gather_facts: no
  connection: network_cli
  vars_prompt:
    - name: username
      prompt: "ahmed123"
      private: yes
    - name: password
      prompt: "ahmed123"
      private: yes
  tasks:
    - name: Configure FastEthernet interfaces
      ios_config:
        lines:
          - interface FastEthernet0/0
          - ip address 20.20.1.1 255.255.255.0
          - no shutdown
          - interface FastEthernet1/0
          - ip address 20.20.2.1 255.255.255.0
          - no shutdown
          - interface FastEthernet2/0
          - ip address 20.20.3.1 255.255.255.0
          - no shutdown
          - interface FastEthernet4/0
          - ip address 192.168.1.200 255.255.255.0
          - no shutdown
      register: result_fastethernet

    - name: Configure SSH and username
      ios_config:
        lines:
          - conf t
          - username {{ username }} secret {{ password }}
          - crypto key generate rsa encryption modulus 1024
          - line vty 0 4
          - transport input ssh
          - login local
      register: result_SSH

    - name: Configure OSPF
      ios_config:
        lines:
          - router ospf 1
          - network 0.0.0.0 255.255.255.255 area 0
      register: result_ospf
