---
- name: Configure network devices
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: run sh ip int br
      panos_cli:
        cmd: show interface management
      register: management_interface_output
