---
- name: Provision Palo Alto Networks firewall and associated resources
  hosts: all
  gather_facts: false

  vars:
    panos_provider:
      hostname: "192.168.1.132"
      username: "admin"
      password: "Ahmed123"  # Added a closing quotation mark here

  tasks:
    - name: Configure general settings
      panos_general_settings:
        provider: "{{ panos_provider }}"
        hostname: "paloalto-1"
        domain: "ahmed.com"
        lifecycle:
          create_before_destroy: true
