---
- name: Create security policies
  hosts: all
  gather_facts: false
  connection: local

  vars:
    device:
      ip_address: "192.168.1.132"
      username: "admin"
      password: "Ahmed123"

  tasks:
    - name: Create second security rule
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        rule_name: 'permit'
        source_zone: ['any']
        destination_zone: ['any']
        source_ip: ['any']
        destination_ip: ['any']
        application: ['any']
        service: ['application-default']
        action: 'allow'
 
