---
- name: Create security policies
  hosts: all
  gather_facts: false
  connection: local

  vars:
    device:
      ip_address: "192.168.1.132"
      username: "admin"
      password: "Ahmed123"

  tasks:
    - name: Create first security rule
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        rule_name: 'permit'
        source_zone: ['any']
        destination_zone: ['any']
        source_ip: ['any']
        destination_ip: ['any']
        application: ['any']
        service: ['application-default']
        action: 'allow'

    - name: Create ethernet interfaces
      paloaltonetworks.panos.panos_interface:
        provider: '{{ device }}'
        interface: ['ethernet1/3']
        if_name: 'ethernet1/3'
        mode: 'layer3'
        zone: 'trust2'
        ip: ['10.1.1.1/24']
        enable_dhcp: false
      register: result

    - name: create DMZ zone on a firewall
      paloaltonetworks.panos.panos_zone:
        provider: '{{ device }}'
        zone: 'trust2'
        mode: 'layer3'
        


        
    - name: create DMZ zone on a firewall
      paloaltonetworks.panos.panos_zone:
        provider: '{{ device }}'
        zone: 'untrust2'
        mode: 'layer3'
        
    # - name: add ethernet1/2 to zone untrust2
    #   paloaltonetworks.panos.panos_interface:
    #     provider: '{{ device }}'
    #     zone: 'untrust2'
    #     mode: 'layer3'
    #     interface: ['ethernet1/2']

 
