---
- name: Provision Palo Alto Networks firewall and associated resources
  hosts: all
  gather_facts: false

  vars:
    device:
      hostname: "192.168.1.132"
      username: "admin"
      password: "Ahmed123"

  tasks:
    - name: Add Security Rule
      panos_security_rule:
        provider: "{{ device }}"
        rule_name: "Allow SSH from Internal to DMZ"
        source_zone: "internal"
        source_ip: "192.168.1.0/24"
        destination_zone: "dmz"
        destination_ip: "10.10.10.0/24"
        destination_port: "22"
        action: "allow"
        log_setting: "log-and-forward"
        description: "Allow SSH traffic from internal to DMZ"
        state: "present"
