---
- name: Provision Palo Alto Networks firewall and associated resources
  hosts: all
  gather_facts: false

  vars:
    device:
      hostname: "192.168.1.132"
      username: "admin"
      password: "Ahmed123"

   interfaces:
      - if_name: 'ethernet1/1'
        mode: 'layer3'
        ip: ['192.168.55.20/24']
      - if_name: 'ethernet1/2'
        mode: 'layer3'
        ip: ['192.168.45.20/24']
      - if_name: 'ethernet1/3'
        mode: 'layer3'
        ip: ['192.168.35.20/24']
