---
- name: Provision Palo Alto Networks firewall and associated resources
  hosts: all
  gather_facts: false

  vars:
    device:
      hostname: "192.168.1.132"
      username: "admin"
      password: "Ahmed123"

  tasks:
    - name: Add Security Rule
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: 'show interface managment'
