---
- name: Provision Palo Alto Networks firewall and associated resources
  hosts: all
  gather_facts: false

  vars:
    device:
      hostname: "192.168.1.132"
      username: "admin"
      password: "Ahmed123"

  tasks:
    - name: Create first security rule
      paloaltonetworks.panos.panos_security_rule:
        provider: '{{ device }}'
        rule_name: 'Prod SSH Inbound'
        source_zone: ['untrust']
        destination_zone: ['trust']
        source_ip: ['any']
        destination_ip: ['Prod-Instances']
        application: ['ssh']
        service: ['application-default']
        action: 'allow'
        tag_name: ['Prod']
        commit: false
