---
- name: Create security policies
  hosts: all
  gather_facts: false
  connection: local

  vars:
    device:
      ip_address: "192.168.1.132"
      username: "admin"
      password: "Ahmed123"

  tasks:
    - name: Create first security rule
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        rule_name: 'permit'
        source_zone: ['any']
        destination_zone: ['any']
        source_ip: ['any']
        destination_ip: ['any']
        application: ['any']
        service: ['application-default']
        action: 'allow'
        
    - name: Create Virtual Router
      paloaltonetworks.panos.panos_virtual_router:
        provider: '{{ device }}'
        name: vr-1
        
    - name: ensure mngt profile trust exists 
      paloaltonetworks.panos.panos_management_profile:
        provider: '{{ device }}'
        name: 'trust'
        ping: true
        ssh: true 
        https: true
        
    - name: ensure mngt profile untrust exists 
      paloaltonetworks.panos.panos_management_profile:
        provider: '{{ device }}'
        name: 'untrust'
        ping: true    

    - name: create trust2 zone on a firewall
      paloaltonetworks.panos.panos_zone:
        provider: '{{ device }}'
        zone: 'trust2'
        mode: 'layer3'
        
    - name: create untrust2 zone on a firewall
      paloaltonetworks.panos.panos_zone:
        provider: '{{ device }}'
        zone: 'untrust2'
        mode: 'layer3'
        
    - name: create VPN zone on a firewall
      paloaltonetworks.panos.panos_zone:
        provider: '{{ device }}'
        zone: 'VPN'
        mode: 'layer3'
    
        
    - name: Create ethernet interfaces
      paloaltonetworks.panos.panos_interface:
        provider: '{{ device }}'
        if_name: 'ethernet1/3'
        mode: 'layer3'
        zone_name: 'trust2'
        vr_name: 'default'
        ip: ['10.1.1.1/24']
        enable_dhcp: false
        management_profile: 'trust'
      register: result

    - name: create tunnel.101
      paloaltonetworks.panos.panos_tunnel:
        provider: '{{ device }}'
        if_name: "tunnel.101"
        zone_name: 'VPN'
        vr_name: 'vr-1'
        management_profile: 'untrust'

    - name: ensure mngt profile trust exists 
      paloaltonetworks.panos.panos_management_profile:
        provider: '{{ device }}'
        name: 'trust'
        ping: true
        ssh: true 
        https: true
        
    - name: ensure mngt profile untrust exists 
      paloaltonetworks.panos.panos_management_profile:
        provider: '{{ device }}'
        name: 'untrust'
        ping: true


    - name: ethernet1/3.50 as static in zone dmz
      paloaltonetworks.panos.panos_l3_subinterface:
        provider: '{{ device }}'
        name: "ethernet1/3.50"
        tag: 50
        enable_dhcp: false
        ip: ["10.1.1.1/24"]
        zone_name: "untrust"
        vr_name: 'default'
        management_profile: 'untrust'

    - name: Create route 'Test-One'
      paloaltonetworks.panos.panos_static_route:
        provider: '{{ device }}'
        name: 'Test-One'
        destination: '1.1.1.0/24'
        nexthop: '10.0.0.1'
        metric: "10"
        virtual_router: "vr-1"

    - name: Create route 'vpn'
      paloaltonetworks.panos.panos_static_route:
        provider: '{{ device }}'
        name: 'ROUTE VPN'
        destination: '1.1.1.0/24'
        interface: 'tunnel.101'
        nexthop_type: 'none'
        metric: "10"
        virtual_router: "vr-1"

    
   




    
        
    # - name: add ethernet1/2 to zone untrust2
    #   paloaltonetworks.panos.panos_interface:
    #     provider: '{{ device }}'
    #     zone: 'untrust2'
    #     mode: 'layer3'
    #     interface: ['ethernet1/2']

 
