---
- name: Configure network devices
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Run 'show interface management' command on PaloAlto firewall
      panos_interface_facts:
        commands: show interface management
      register: management_interface_output
