---
- name: Create security policies
  hosts: all
  gather_facts: false
  connection: local

  vars:
    device:
      ip_address: "192.168.1.132"
      username: "admin"
      password: "Ahmed123"

  tasks:
    - name: Add example rule 1
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        source_zones: ["any"]
        source_addresses: ["any"]
        source_users: ["any"]
        destination_zones: ["any"]
        destination_addresses: ["any"]
        applications: ["any"]
        services: ["application-default"]
        categories: ["any"]
        action: "allow"
 
